# Generated by Django 3.1.2 on 2021-11-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://media.istockphoto.com/vectors/all-seeing-eye-icon-eye-in-triangle-illuminati-mason-symbol-vector-vector-id1265037182?k=20&m=1265037182&s=170667a&w=0&h=lZ4GKha5J9UNqLsIilcKSzQgrn8cm_teitVKYXlxW_w=', max_length=300),
        ),
    ]
