# Generated by Django 3.1.2 on 2021-11-07 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211105_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='San Francisco', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main_app.city'),
        ),
    ]
